config/routes.rb
Taskitoff::Application.routes.draw do

 devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	 resources :todos do

	  post 'complete', to: 'todos#complete'
	 
	 end

  root :to => 'todos#index' 

  match 'completed' => 'todos#completed'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  #def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    
   # user ||= User.new # guest user

    # if a member, they can manage their own posts 
    # (or create new ones

    #if user.member?
     # can :manage, :all
    #else
    #  can :read, :all
    #end

     #ROLES = %w[member moderator admin]
    #def role?(base_role)
    #  role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
   # end
#
   # private

    #def set_member
   #   self.role = 'member'
    #end
  #end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	attr_accessible :description, :name

	belongs_to :user

	validates :name, length: { maximum: 25 }

	scope :alive, where( 'created_at > ?', Time.now - 7.days ) 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
	       :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :created_at, :uid, :provider
  # attr_accessible :title, :body

  has_many :todos, dependent: :destroy

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  	user = User.where(:provider => auth.provider, :uid => auth.uid).first
  	unless user
  		pass = Devise.friendly_token[0,20]
  		user = User.new(name: auth.extra.raw_info.name,
  									provide: auth.provider,
  									uid: auth.id,
										email: auth.info.email,
										password: pass,
										password_confirmation: pass
						  			)
  		user.skip_confirmation!
  		user.save
		end
		user
	end
  		
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    todos_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def no
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
   respond_to :html, :js

  def index

    if user_signed_in? 
      @todos = current_user.todos.where(:completed => false)
    end
  end

  def show
  	@todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(params[:todo])
    @todo.user = current_user
    @todo.completed = false
    if @todo.save
      redirect_to todos_path, notice: "Todo was saved successfully. Now get to work!"
    else
      flash[:error] = "Sorry bud, but there was an error. Please try using less words in your title"
      render :new
    end

    #respond_with(@todo) do |f|
     # f.html 
    #end

  end

  def destroy
    @todo = Todo.find(params[:id])
    name = @todo.name

    if @todo.destroy
      flash[:notice] = "\"#{name}\" was removed successfully."
      redirect_to todos_path
    else
      flash[:error] = "There was an error removing the topic."
      redirect_to todos_path
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update_attributes(params[:todo])
      redirect_to todos_path
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end    
  end

  def complete
    Todo.find(params[:todo_id]).update_attribute(:completed, true) 
    redirect_to todos_path 
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			sign_up_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper

	def time_to_self_destruct(todo)
		f = Time.now
		distance_of_time_in_words( f , todo.created_at + 7.days )
	end

end

app/views/layouts/application.html.erb
<html>
<head>
  <title>Taskoff</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
    <% if current_user %>
			<li><%= link_to "Task Off", root_path, class: "navbar-brand" %></li>
      <li><%= link_to "Completed Task", completed_path, class: "navbar-brand" %></li>
      <div class="pull-right user-info">
         	Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
              <i class="icon-share-alt"> </i>
          <% end %>
          
	      <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>
     </div>


		</ul>

	</div>

	<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>


</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <div class="container">
   <h1>Welcome to Taskoff</h1>
   <p>The app where your self destruct in 7 days</p>
   <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or 
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <div class="container">
   <h1>Welcome to Taskoff</h1>
   <p>The app where your task blast off in 7 days</p>
   <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or 
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
  </div>
</div>


<ul class="list-group">
  <li class="list-group-item">As a user, I should be able to sign up for a free account by providing a user name, password and email address.</li>
  <li class="list-group-item">As a user, I want to be able to sign in and out of the taskitoff.
	</li>
	  <li class="list-group-item">As a user, I want to be able to create a single to-do list.
	</li>
	  <li class="list-group-item">As a user, I want to be able to create multiple items on my to-do list.
	</li>
	  <li class="list-group-item">As a user, I want to be able to mark items on my to-do list as complete.
	</li>
	<li class="list-group-item">Items on a to-do list should automatically self-destruct after 7 days from their creation.

	</li>
</ul>

app/views/pages/no.hmtl.erb
<%= image_tag(http://www.cutensweet.com/wp-content/uploads/2012/02/cute-sad-baby.jpeg) %>

app/views/todos/_form.html.erb
<%= form_for todo do |f| %>

  <form role="form">
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, placeholder: "Every task needs a name", class: 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, placeholder: "What do you want to accomplish?", class: 'form-control' %>
      </div>
    </div>
    </br>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Save", class: 'btn-success' %>
      </div>
    </div>
  </form>
<% end %>

app/views/todos/completed.html.erb
	<div class="panel panel-primary">
	  <!-- Default panel contents -->
	  <div class="panel-heading">
	  	Completed <%= current_user.todos.where(:completed => true ).count %> task within only 7 days.
	  </div>
		  <!-- Table -->
		  <table class="table table-striped table-bordered table-condensed">
				<p><% @todos = current_user.todos.where(:completed => true ) %></p>
				<tr>
				  	<th><%="#" %></th>
						<th> Name </th>
						<th> Description </th>
						<th>Remove from completed list</th>
				</tr> 
				  <% @todos.each do |todo| %>
				<tr>
				  	<td><%= todo.id %></td>
				  	<td><%= todo.name %></td>
						<td><%= todo.description %></td>
						<td><%= link_to "I don't like looking at this, please remove", todo, method: :delete , class: "btn btn-danger" %></td>
				</tr>
					<% end %>
			</table>
	</div>

app/views/todos/create.js.erb
<% if @todo.valid? %>
  $(".js-comments").prepend("<%= escape_javascript(render(@todo)) %>");
<% else %>
  $(".js-new-todo").replaceWith("<%= escape_javascript(render partial: 'form', locals: { todo: @todo }) %>");
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todos</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<% if user_signed_in? %>
	<div class="panel panel-primary">
	  <!-- Default panel contents -->
	  <div class="panel-heading">
	  	Add items to your task list, but make sure they can get done within 7 days.
	  </div>
		  <!-- Table -->
		  <table class="table table-striped table-bordered table-condensed">
		  		<tr>
			    	<th><%="#" %></th>
		  			<th> Name </th>
		  			<th> Description </th>
		  			<th> Time Left </th>
		  			<th>Completed?</th>
		  			<th>Delete</th>
	  			</tr> 
		    <% @todos.each do |todo| %>
		    	<tr>
			    	<td><%= todo.id %></td>
			    	<td><%= todo.name %></td>
		    		<td><%= todo.description %></td>
		    		<td><%= time_to_self_destruct(todo) %> left </td>
		    		
		    		<td><%= link_to "Oh Yeah! Got it done", todo_complete_path(todo), method: :post , class: "btn btn-warning" %></td>
		    		
		    		<td><%= link_to "I can't do this, please remove", todo, :confirm => 'Are you sure? You can do this!', method: :delete , class: "btn btn-danger" %></td>

		    	</tr>
				<% end %>
		  </table>
		<br/>
		<a href="#" class="js-show-hide" data-selector="js-new-todo">Add a task</a>
		
  <br/>
   <div class="js-new-todo hide">
			<%= render partial: 'form', locals: {todo: Todo.new} %>
	 </div>
<% end %>

app/views/todos/new.html.erb
<h1>Add a Task</h1>

<%= form_for @todo do |f| %>

  <form role="form">
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
    	  <%= f.text_field :name, placeholder: "Every task needs a name" %>
    	</div>
    </div>
    <div class="control-group">
      <%= f.label :description, class: 'control-label' %>
      <div class="controls">
    	  <%= f.text_field :description, placeholder: "What do you want to accomplish?" %>
  	  </div>
    </div>
    </br>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Save", class: 'btn-success' %>
      </div>
    </div>
  </form>
<% end %>

app/views/todos/show.html.erb
<div class="jumbotron">
  
    <%= @todo.name %>
    <%= @todo.description %>

    <hr/>
	
</div>